print('welcome to mablibs by soda')
name1 = input("Enter a name: ")
name2 = input("Enter another name: ")
#noun1 = input("Enter a noun: ")
place1 = input("Enter a place: ")
adjective1 = input("Enter a adjective: ")
adjective2 = input("Enter another adjective: ")
animal1 = input("Enter an animal: ")
food1 = input("Enter a food: ")
verb1 = input("Enter a verb: ")
number1 = input("Enter a number: ")
number2 = input("Enter another number: ")


print("Once upon a time there was a man named "+name1+" that lived on a "+place1+".")
print("He raises a lot of animals but his favorite one was his "+adjective1+ chr(32)+ adjective2 +chr(32)+ animal1 +" named " +name2+".")
print("Every morning he would feed his "+adjective1 +chr(32)+animal1 +chr(32)+food1+" that was left over from the previous night.")
print("Sometimes when "+name1+" comes out of the house "+name1+" would see "+adjective1 +chr(32)+adjective2+chr(32)+ name2+" walking around the barn and pecking for "+food1+".")
print(number1+" years later "+name2+" laid eggs and had "+number2+" babies. They all lived at the "+place1+" together and ate "+food1+".")