
print('welcome to mablibs by soda')
name1 = input("Enter a name: ")
name2 = input("Enter another name: ")
#noun1 = input("Enter a noun: ")
#place1 = input("Enter a place: ")
country1 = input("Enter a country: ")
adjective1 = input("Enter a adjective: ")
#adjective2 = input("Enter another adjective: ")
animal1 = input("Enter an animal: ")
food1 = input("Enter a food: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter a verb: ")
#number1 = input("Enter a number: ")
#number2 = input("Enter another number: ")

print("Once upon a time there was a "+noun1+" named "+name1+". He had a daughter named "+name2+".")
print("And they lived in a "+country1+" jungle. One day, a "+adjective1+chr(32)+animal1+" came and tried to "+verb1+" his daughter.")
print("But he "+verb2+" the "+adjective1+chr(32)+animal1+" up in pieces for dinner. "+name1+" and "+name2+" ate the "+animal1+" with "+food1)
